### ISSUE TITLE
 av_guess_format() error: Could not guess output format for

### ISSUE THREAD

**Issue by longcheng-wangxj** [eguid/easyCV#10]
录像输出 我配置的--------D:home//RmadFile//html/testq，是不是有问题啊

**Comment by longcheng-wangxj** [comment]
/*
	 * 保存任务并初始化录制器
	 * @param task
	 * @throws CloneNotSupportedException
	 * @throws IOException
	 */
	private void saveTaskAndinitRecorder(RecordTask task) throws CloneNotSupportedException, IOException {
		Recorder recorder=task.getRecorder();
		recorder.from(task.getSrc()).to(task.getOut());//重新设置视频源和输出
		workpool.add(task);
		//由于使用的是池中的引用，所以使用克隆用于保存副本
	
		work_size++;//工作池数量增加
	}

**Comment by eguid** [comment]
D:home//RmadFile//html/testq，这个地址恐怕任何程序都识别不了

**Comment by longcheng-wangxj** [comment]
没仔细看 你的说明 我以为 直接 new file   到本地了！  我用nginx 实现下！
