### ISSUE TITLE
接入hls协议视频流截图时，截图出现了全黑图片，请问这是视频源网络不稳定造成的，还是其他原因呢？您这边是否有解决方案呢？另外，debug跟踪代码时，发现在打开视频源时，接入的视频流长度只有2，如何更改这个长度呢？

### ISSUE THREAD

**Issue by 752050240** [eguid/easyCV#2]
/**
	 * 打开视频流
	 * @param url -url
	 * @return
	 * @throws FileNotOpenException
	 */
	protected avformat.AVFormatContext openInput(String url) throws FileNotOpenException {

		avformat.AVFormatContext pFormatCtx = new avformat.AVFormatContext(null);
        int length = pFormatCtx.nb_streams();//这里为何一直时固定值2，如何更改此处值呢？
        if(avformat_open_input(pFormatCtx, url, null, null)==0) {
			return pFormatCtx;
		}
		throw new FileNotOpenException("Didn't open video file");
	}

**Comment by 752050240** [comment]
接入hls协议视频流截图时，截图出现了全黑图片，请问这是视频源网络不稳定造成的，还是其他原因呢？您这边是否有解决方案呢？另外，debug跟踪代码时，发现在打开视频源时，接入的视频流长度只有2，如何更改这个长度呢？

**Comment by eguid** [comment]
这里的流数量是2表示有视频流和音频流两个流，在下面的findVideoStreamIndex()方法中的if (type == AVMEDIA_TYPE_VIDEO)以及if (type == AVMEDIA_TYPE_AUDIO) 判断了两个流中哪一个是视频流哪一个是音频流
