### ISSUE TITLE
录制本机电脑屏幕指定区域怎么实现

### ISSUE THREAD

**Issue by 512433465** [eguid/easyCV#3]

**Comment by eguid** [comment]
请参考我的博客关于屏幕录制功能得实现：https://blog.csdn.net/eguid_1/article/details/64922443

**Comment by 512433465** [comment]
> 请参考我的博客关于屏幕录制功能得实现：https://blog.csdn.net/eguid_1/article/details/64922443

老铁，非常哇塞，我想把这个录制结果保存下来，该怎么办呢？麻烦大佬点拨一下下，非常感谢~

**Comment by eguid** [comment]
要结合javacv的Recorder进行录制，具体也参考我的博客：https://blog.csdn.net/eguid_1/article/details/52680802
另外还可以参考ffmpeg命令方式屏幕录制为mp4文件（这种不用写代码）：https://blog.csdn.net/eguid_1/article/details/83000705

**Comment by 512433465** [comment]
多谢，大佬指点，我去学习一下

**Comment by balalaxiao** [comment]
大佬，有用web实现的吗

**Comment by eguid** [comment]
> 
> 
> 大佬，有用web实现的吗

web屏幕录制？没有
