### ISSUE TITLE
Question about FPS

### ISSUE THREAD

**Issue by hulin17** [eguid/easyCV#4]
As I use your code, the fps is 0.5/s. I want to change the FPS, but it didn't work. Can you give me some advice?

**Comment by eguid** [comment]
Not Know if you are calling video or screenshot lib?

**Comment by hulin17** [comment]
Thanks for your reply firstly.I use the screenshot lib to cut images from RTSP URL. I changed the code as follows 
![image](https://user-images.githubusercontent.com/31561654/60854596-70bd5980-a233-11e9-8b0f-c92cb5e8f697.png)

**Comment by hulin17** [comment]
I use a camera which is 25 fps. In your code "packet.flags == AV_PKT_FLAG_KEY" get the key frame and filter the others.   However I want to adjust the FPS of Getting Frames Dynamically in a second.  Very Thankful to get your reply!

**Comment by eguid** [comment]
Yes, you can decode non-keyframes, not filter keyframes,but ffmpeg can't decode 'B frames',so you must filter 'B frames' and decode 'P' frames to achieve this function.
I hope this helps you.

**Comment by hulin17** [comment]
I know what is your meaning.What puzzles me is that there are 29 non-key Frames and 1 key frame in two seconds(in my case).For example I set the FPS = 3, then I need to get 6 pictures in the 30 frames which are P0,P5,P10,P15,P20,P25,P30 and the others should be filtered.  Actually I don't know how to filter the others because the packet seems to have no timestamp... Can you show me the code of this part?

**Comment by eguid** [comment]
I don't have these code yet.
I know that some camera devices get video frames without timestamp because them video frames are sent in order, so you can also decode by serial number.
For example, video 'FPS' is 30,if you set FPS = 3, you can select P0, P10, P20,P30,P40,P50... for decoding.

**Comment by hulin17** [comment]
I have used the way you said, it did't work. There are interrupts between images，at 11:30:48 there are
tens of images, then at 11:30:59 there are tens of images.  Between 11:30:48 to 11:30:59, No images.I am so confused that I have to ask for your help.so sad...
![image](https://user-images.githubusercontent.com/31561654/60858571-7ae65480-a241-11e9-9956-0b42aea6fe6c.png)
In addition, FFmpeg command has property as "-vf fps=5". Is there function in this"org.bytedeco.javacpp" ? Sorry for my stupid...

**Comment by eguid** [comment]
I have updated the code according to the new ffmpeg api to better support the screenshot function. Now you can try again if there are still problems with the continuous screenshot. I hope to help you.

**Comment by hulin17** [comment]
It's very kind of you!!! I'll try it. Thank you anyway!

**Comment by eguid** [comment]
I have added a continuous screenshot feature in this update, Hope this is useful to you.
