### ISSUE TITLE
运行的时候报以下错误，是还需要安装单独的数据库吗？

### ISSUE THREAD

**Issue by shelimingming** [eguid/easyCV#5]
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by shelimingming** [comment]
安装了PostgreSql数据库还是报这个错，请教一下，还需要什么操作？

**Comment by eguid** [comment]
按照你的错误提示的话是由于没有设置spring.datasource.url

**Comment by shelimingming** [comment]
这个程序能做到录像或者拍照的时候在浏览器中有预览吗？就是能在浏览器中看到拍照的过程

**Comment by eguid** [comment]
拍照过程指的是什么？
项目里有提供两个截图web服务的demo，里面有涉及这块你说的拍照（截图）这块，具体效果可以打开demo看一下

**Comment by shelimingming** [comment]
多谢多谢！
