### ISSUE TITLE
本机有两块显卡（0、1），使用FFmpegFrameGrabber  对指定某块显卡怎么设置，.setOption("hwaccel_device", "0");并没有起作用，使用ffmpeg 可以正常指定

### ISSUE THREAD

**Issue by yangqx** [eguid/easyCV#7]

**Comment by yangqx** [comment]
FFmpegFrameGrabber ff = new FFmpegFrameGrabber(url);
ff.setVideoOption("gpu","0")

**Comment by eguid** [comment]
Please allow me to open this question to help more developers.
Thanks.
