### ISSUE TITLE
demo中只涉及到截图和录像信息的表结构都是简单的单表，可以通过*Mapper.xml文件查看表结构

### ISSUE THREAD

**Issue by longcheng-wangxj** [eguid/easyCV#9]
demo中只涉及到截图和录像信息的表结构都是简单的单表，可以通过*Mapper.xml文件查看表结构

_Originally posted by @eguid in https://github.com/eguid/easyCV/issues/8#issuecomment-518063673_  数据库换成 mysql  也没什么问题吧！

**Comment by eguid** [comment]
没问题
